### ISSUE TITLE
how can user disable nested directory view?

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#208]
![image](https://user-images.githubusercontent.com/32936898/80856909-9b741500-8c80-11ea-9870-4fe548928ae9.png)

![image](https://user-images.githubusercontent.com/32936898/80856917-a8910400-8c80-11ea-8b12-c4ab61722ce5.png)

thanks!

**Comment by Andrflor** [comment]
Hi,
At the moment the fact that you got that view is a bug introduced by #207

You can fix it by using defx from the previous commit 1fb1d5f9b09ff6da815dfcdf3dfcb277605b9650

@Shougo Thx for the great reactivity, thus the modification introduced a bug...
If a folder only contains one file it's processed as if it was a nested folder.

**Comment by Shougo** [comment]
Thanks.  I have fixed it.

**Comment by kristijanhusak** [comment]
@Shougo how can I now create/move/copy files to the empty directories in between?

For example, I cannot copy `rplugin/python3/deoplete/source/file.py` to `rplugin/file.py`. I tried copying, pasting, pick to rename, and change full path to the one above, but it throws an error that still exists. We should either have a flag for this option or have a way to work with folders in between.

**Comment by Freed-Wu** [comment]
> For example, I cannot copy rplugin/python3/deoplete/source/file.py to rplugin/file.py. I tried copying, pasting, pick to rename, and change full path to the one above, but it throws an error that still exists.

i cannot do, too.

![image](https://user-images.githubusercontent.com/32936898/80894433-7974a400-8d0d-11ea-87bf-a26339127756.png)

**Comment by Shougo** [comment]
> @Shougo how can I now create/move/copy files to the empty directories in between?

You can disable the feature by `open_tree_recursive` action.
But I may add the option for it.

**Comment by Shougo** [comment]
I have added nested option for nested feature.
And the default behavior is restored.
