### ISSUE TITLE
defx messes window layout

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#95]
Consider the following minimal `init.vim`
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
```
Now as in the GIF do the following
1. Open `nvim` and edit some file, for example `:e init.vim`
2. Run `sp` and then `vsp`
3. Run `:Defx`
4. Run `:q` on the defx buffer
You can see in steps 3 and 4 that window layout is broken -> defx shouldn't change the window layout

![defxlayout](https://user-images.githubusercontent.com/2583971/54086764-30a0a580-432b-11e9-8987-48425bf1f1e4.gif)

**Comment by Shougo** [comment]
> Run :q on the defx buffer

`:q` is not supported.   Please use `quit` action instead.

**Comment by Shougo** [comment]
defx is not magic.

**Comment by petobens** [comment]
Thank  you!

**Comment by petobens** [comment]
This is indeed working with `defx#do_action('quit')` but not when opening files. Consider the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    nnoremap <silent><buffer><expr> q defx#do_action('quit')
    nnoremap <silent><buffer><expr> <CR>
        \ defx#is_directory() ? defx#do_action('open') :
        \ defx#do_action('multi', ['drop', 'quit'])
endfunction
```
Now
1. Open nvim and edit some file, for example `:e init.vim`
2. Run `:sp`, move to the new split and run `:vsp`, move to this new split and run `:sp` again.
3. From the last split window run `:Defx`
4. Press `<CR>` on some candidate

After 4. the original window layout is broken (on the other hand if using `q` instead of `<CR>` then the layout is indeed preserved)

**Comment by Shougo** [comment]
I have fixed the problem.   Please use the latest version.

**Comment by petobens** [comment]
Thanks! This is now working for `quit` and `<CR>` but not working with splits. Using the same minimal vimrc as above add 
```
    nnoremap <silent><buffer><expr> s
        \ defx#do_action('multi', [['drop', 'split'], 'quit'])
```
and repeat the steps but instead of pressing `q` or `CR` press `s` -> the layout is still broken

**Comment by Shougo** [comment]
Please use the latest version.

**Comment by petobens** [comment]
Still not working unfortunately

**Comment by Shougo** [comment]
Oh,  OK.  If so, it is feature.
Split is not supported.

**Comment by petobens** [comment]
Ok. Thanks anyways
